spring:
  application:
    name: coldroommonitor
  datasource:
    url: jdbc:postgresql://localhost:5432/coldroomdb
    username: coldroommonitor
    password: 9kd#absk@34S
  jpa:
    hibernate:
      ddl-auto: update # en dev; luego cambiar a validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug